// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SteamDbContext))]
    [Migration("20260710093033_UpdateEnitityUserGame")]
    partial class UpdateEnitityUserGame
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AchievementUser", b =>
            {
                b.Property<int>("AchievementsId")
                    .HasColumnType("int");

                b.Property<string>("UsersId")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("AchievementsId", "UsersId");

                b.HasIndex("UsersId");

                b.ToTable("AchievementUser");
            });

            modelBuilder.Entity("DataAccess.Data.Entities.Achievement", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("GameId")
                    .HasColumnType("int");

                b.Property<string>("IconUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("GameId");

                b.ToTable("Achievements");

                b.HasData(
                    new
                    {
                        Id = 1,
                        GameId = 1,
                        IconUrl = "https://example.com/icons/first_blood.png",
                        Name = "First Blood"
                    },
                    new
                    {
                        Id = 2,
                        GameId = 2,
                        IconUrl = "https://example.com/icons/hacker.png",
                        Name = "Master Hacker"
                    },
                    new
                    {
                        Id = 3,
                        GameId = 3,
                        IconUrl = "https://example.com/icons/elden_lord.png",
                        Name = "Lord of Frenzied Flame"
                    });
            });

            modelBuilder.Entity("DataAccess.Data.Entities.Game", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("CoverImage")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DeveloperId")
                    .HasColumnType("nvarchar(450)");

                b.Property<decimal>("Price")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTime>("ReleaseDate")
                    .HasColumnType("datetime2");

                b.Property<string>("SystemRequirements")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("DeveloperId");

                b.ToTable("Games");

                b.HasData(
                    new
                    {
                        Id = 1,
                        CoverImage = "https://example.com/covers/cs2.jpg",
                        Description = "Tactical shooter.",
                        Price = 0.00m,
                        ReleaseDate = new DateTime(2023, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        SystemRequirements = "Windows 10, 8GB RAM",
                        Title = "Counter-Strike 2"
                    },
                    new
                    {
                        Id = 2,
                        CoverImage = "https://example.com/covers/neon.jpg",
                        Description = "Cyberpunk RPG.",
                        Price = 29.99m,
                        ReleaseDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        SystemRequirements = "Windows 11, 16GB RAM",
                        Title = "Neon City 2026"
                    },
                    new
                    {
                        Id = 3,
                        CoverImage = "https://example.com/covers/elden.jpg",
                        Description = "Rise, Tarnished.",
                        Price = 59.99m,
                        ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        SystemRequirements = "Windows 10, RTX 2060",
                        Title = "Elden Ring"
                    });
            });

            modelBuilder.Entity("DataAccess.Data.Entities.GameVersion", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("GameId")
                    .HasColumnType("int");

                b.Property<string>("PatchNotes")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Version")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("GameId");

                b.ToTable("GameVersions");

                b.HasData(
                    new
                    {
                        Id = 1,
                        GameId = 1,
                        PatchNotes = "Initial release.",
                        Version = "v1.0"
                    },
                    new
                    {
                        Id = 2,
                        GameId = 1,
                        PatchNotes = "Fixed smoke grenades.",
                        Version = "v1.1"
                    },
                    new
                    {
                        Id = 3,
                        GameId = 2,
                        PatchNotes = "Early Access Launch.",
                        Version = "v0.9"
                    },
                    new
                    {
                        Id = 4,
                        GameId = 3,
                        PatchNotes = "Colosseum update.",
                        Version = "v1.10"
                    });
            });

            modelBuilder.Entity("DataAccess.Data.Entities.Profile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Avatar")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Badges")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Level")
                    .HasColumnType("int");

                b.Property<string>("Showcase")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("XP")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("UserId")
                    .IsUnique();

                b.ToTable("Profiles");
            });

            modelBuilder.Entity("DataAccess.Data.Entities.Screenshot", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("GameId")
                    .HasColumnType("int");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("GameId");

                b.ToTable("Screenshots");

                b.HasData(
                    new
                    {
                        Id = 1,
                        GameId = 1,
                        Url = "https://example.com/screenshots/cs2_1.jpg"
                    },
                    new
                    {
                        Id = 2,
                        GameId = 1,
                        Url = "https://example.com/screenshots/cs2_2.jpg"
                    },
                    new
                    {
                        Id = 3,
                        GameId = 2,
                        Url = "https://example.com/screenshots/neon_1.jpg"
                    },
                    new
                    {
                        Id = 4,
                        GameId = 3,
                        Url = "https://example.com/screenshots/elden_1.jpg"
                    });
            });

            modelBuilder.Entity("DataAccess.Data.Entities.Tag", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Picture")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Tags");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Name = "Action"
                    },
                    new
                    {
                        Id = 2,
                        Name = "Co-op"
                    },
                    new
                    {
                        Id = 3,
                        Name = "Cyberpunk"
                    },
                    new
                    {
                        Id = 4,
                        Name = "Souls-like"
                    });
            });

            modelBuilder.Entity("DataAccess.Data.Entities.User", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("int");

                b.Property<string>("Bio")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Country")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("bit");

                b.Property<DateTime>("LastOnline")
                    .HasColumnType("datetime2");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("PasswordHash")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("bit");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<int>("UserRole")
                    .HasColumnType("int");

                b.Property<int>("UserVisibility")
                    .HasColumnType("int");

                b.Property<decimal>("WalletBalance")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex")
                    .HasFilter("[NormalizedUserName] IS NOT NULL");

                b.ToTable("Users", (string)null);
            });

            modelBuilder.Entity("DataAccess.Data.Entities.UserGame", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("GameId")
                    .HasColumnType("int");

                b.Property<bool>("IsInstalled")
                    .HasColumnType("bit");

                b.Property<int>("PlayTimeMinutes")
                    .HasColumnType("int");

                b.Property<DateTime>("PurchasedAt")
                    .HasColumnType("datetime2");

                b.HasKey("UserId", "GameId");

                b.HasIndex("GameId");

                b.ToTable("UserGames");
            });

            modelBuilder.Entity("GameTag", b =>
            {
                b.Property<int>("GamesId")
                    .HasColumnType("int");

                b.Property<int>("TagsId")
                    .HasColumnType("int");

                b.HasKey("GamesId", "TagsId");

                b.HasIndex("TagsId");

                b.ToTable("GameTag");

                b.HasData(
                    new
                    {
                        GamesId = 1,
                        TagsId = 1
                    },
                    new
                    {
                        GamesId = 1,
                        TagsId = 2
                    },
                    new
                    {
                        GamesId = 2,
                        TagsId = 1
                    },
                    new
                    {
                        GamesId = 2,
                        TagsId = 3
                    },
                    new
                    {
                        GamesId = 3,
                        TagsId = 1
                    },
                    new
                    {
                        GamesId = 3,
                        TagsId = 4
                    });
            });

            modelBuilder.Entity("GameUser", b =>
            {
                b.Property<string>("UserWishlistId")
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("WishlistId")
                    .HasColumnType("int");

                b.HasKey("UserWishlistId", "WishlistId");

                b.HasIndex("WishlistId");

                b.ToTable("GameUser");
            });

            modelBuilder.Entity("GameUser1", b =>
            {
                b.Property<int>("CartId")
                    .HasColumnType("int");

                b.Property<string>("UserCartId")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("CartId", "UserCartId");

                b.HasIndex("UserCartId");

                b.ToTable("GameUser1");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex")
                    .HasFilter("[NormalizedName] IS NOT NULL");

                b.ToTable("Roles", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RoleId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("RoleClaims", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("UserClaims", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ProviderKey")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("UserLogins", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("RoleId")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("UserRoles", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("LoginProvider")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Value")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("UserTokens", (string)null);
            });

            modelBuilder.Entity("AchievementUser", b =>
            {
                b.HasOne("DataAccess.Data.Entities.Achievement", null)
                    .WithMany()
                    .HasForeignKey("AchievementsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("DataAccess.Data.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UsersId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("DataAccess.Data.Entities.Achievement", b =>
            {
                b.HasOne("DataAccess.Data.Entities.Game", "Game")
                    .WithMany("Achievements")
                    .HasForeignKey("GameId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Game");
            });

            modelBuilder.Entity("DataAccess.Data.Entities.Game", b =>
            {
                b.HasOne("DataAccess.Data.Entities.User", "Developer")
                    .WithMany("DevelopedGames")
                    .HasForeignKey("DeveloperId");

                b.Navigation("Developer");
            });

            modelBuilder.Entity("DataAccess.Data.Entities.GameVersion", b =>
            {
                b.HasOne("DataAccess.Data.Entities.Game", "Game")
                    .WithMany("Versions")
                    .HasForeignKey("GameId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Game");
            });

            modelBuilder.Entity("DataAccess.Data.Entities.Profile", b =>
            {
                b.HasOne("DataAccess.Data.Entities.User", "User")
                    .WithOne("Profile")
                    .HasForeignKey("DataAccess.Data.Entities.Profile", "UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("DataAccess.Data.Entities.Screenshot", b =>
            {
                b.HasOne("DataAccess.Data.Entities.Game", "Game")
                    .WithMany("Screenshots")
                    .HasForeignKey("GameId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Game");
            });

            modelBuilder.Entity("DataAccess.Data.Entities.UserGame", b =>
            {
                b.HasOne("DataAccess.Data.Entities.Game", "Game")
                    .WithMany("UserGames")
                    .HasForeignKey("GameId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("DataAccess.Data.Entities.User", "User")
                    .WithMany("UserGames")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Game");

                b.Navigation("User");
            });

            modelBuilder.Entity("GameTag", b =>
            {
                b.HasOne("DataAccess.Data.Entities.Game", null)
                    .WithMany()
                    .HasForeignKey("GamesId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("DataAccess.Data.Entities.Tag", null)
                    .WithMany()
                    .HasForeignKey("TagsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("GameUser", b =>
            {
                b.HasOne("DataAccess.Data.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserWishlistId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("DataAccess.Data.Entities.Game", null)
                    .WithMany()
                    .HasForeignKey("WishlistId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("GameUser1", b =>
            {
                b.HasOne("DataAccess.Data.Entities.Game", null)
                    .WithMany()
                    .HasForeignKey("CartId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("DataAccess.Data.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserCartId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("DataAccess.Data.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("DataAccess.Data.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("DataAccess.Data.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("DataAccess.Data.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("DataAccess.Data.Entities.Game", b =>
            {
                b.Navigation("Achievements");

                b.Navigation("Screenshots");

                b.Navigation("UserGames");

                b.Navigation("Versions");
            });

            modelBuilder.Entity("DataAccess.Data.Entities.User", b =>
            {
                b.Navigation("DevelopedGames");

                b.Navigation("Profile");

                b.Navigation("UserGames");
            });
#pragma warning restore 612, 618
        }
    }
}